#!/bin/bash
# =============================================================================
# LiveLens — GCP Project Setup Script
# Run this on your local machine to configure all GCP resources
# =============================================================================

set -e

# ---- CONFIGURE THESE ----
PROJECT_ID="${1:?Usage: ./setup_gcp.sh <PROJECT_ID>}"
REGION="us-central1"
BUCKET_NAME="${PROJECT_ID}-livelens"

echo "============================================"
echo " LiveLens GCP Setup"
echo " Project: ${PROJECT_ID}"
echo " Region:  ${REGION}"
echo "============================================"

# Set active project
echo "[1/7] Setting active project..."
gcloud config set project "${PROJECT_ID}"

# Enable required APIs
echo "[2/7] Enabling APIs (this may take a minute)..."
gcloud services enable \
  aiplatform.googleapis.com \
  run.googleapis.com \
  firestore.googleapis.com \
  storage.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  secretmanager.googleapis.com

# Create Cloud Storage bucket
echo "[3/7] Creating Cloud Storage bucket..."
if gsutil ls -b "gs://${BUCKET_NAME}" 2>/dev/null; then
  echo "  Bucket already exists, skipping."
else
  gsutil mb -l "${REGION}" "gs://${BUCKET_NAME}"
  echo "  Created: gs://${BUCKET_NAME}"
fi

# Create Firestore database (if not exists)
echo "[4/7] Setting up Firestore..."
if gcloud firestore databases describe --database="(default)" 2>/dev/null; then
  echo "  Firestore default database already exists, skipping."
else
  gcloud firestore databases create --location=nam5 --type=firestore-native
  echo "  Created Firestore database."
fi

# Create Artifact Registry
echo "[5/7] Creating Artifact Registry repository..."
if gcloud artifacts repositories describe livelens --location="${REGION}" 2>/dev/null; then
  echo "  Repository already exists, skipping."
else
  gcloud artifacts repositories create livelens \
    --repository-format=docker \
    --location="${REGION}" \
    --description="LiveLens container images"
  echo "  Created: livelens repository."
fi

# Set up application default credentials
echo "[6/7] Configuring authentication..."
echo "  Run this separately if needed: gcloud auth application-default login"

# Generate .env file for backend
echo "[7/7] Generating backend .env file..."
cat > backend/.env << EOF
# Auto-generated by setup_gcp.sh
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
GOOGLE_CLOUD_LOCATION=${REGION}
GOOGLE_GENAI_USE_VERTEXAI=True

LIVE_MODEL=gemini-live-2.5-flash-native-audio
REPORT_MODEL=gemini-2.5-flash

GCS_BUCKET_NAME=${BUCKET_NAME}

DEBUG=true
CORS_ORIGINS=["http://localhost:5173","http://localhost:3000"]
EOF

echo ""
echo "============================================"
echo " ✅ GCP Setup Complete!"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. cd backend && python -m venv .venv && source .venv/bin/activate"
echo "  2. pip install -r requirements.txt"
echo "  3. uvicorn app.main:app --reload --port 8000"
echo ""
echo "  4. cd frontend && npm install && npm run dev"
echo ""
echo "Your .env file has been created at backend/.env"
echo "GCS bucket: gs://${BUCKET_NAME}"
echo ""
